#!/bin/bash
# YouTube d=64 K=5: hyperbolic triangle ratio, NO temperature.
#   s(u,v) = ( rad(P_v) - d_H(P_u,P_v) ) / rad(P_u)
PY=/its/home/ms2420/tempest-embeddinng/venv/bin/python
WD=/its/home/ms2420/tempest-embeddinng
LOG=$WD/logs/triangle_ratio/d64_k5/run_2_pat5/YouTube.log
cd "$WD" || exit 1
mkdir -p "$(dirname "$LOG")"
SHA=$(git rev-parse --short HEAD); BRANCH=$(git rev-parse --abbrev-ref HEAD)
DIRTY=$(git status --porcelain --untracked-files=no | head -1)
CMD="$PY -u scripts/train_link_property_prediction.py --data-suite tgb-seq --dataset YouTube \
--d-emb 64 --k-train 5 --lr 1e-3 --num-epochs 100 --early-stop-patience 5 \
--use-gpu --use-gpu-tempest"
{
  echo "# dataset=YouTube (NON-bipartite) d_emb=64 k_train=5  lr=1e-3 (single group)  seed=42"
  echo "# experiment=triangle_ratio cell=d64_k5 tag=run_2_pat5"
  echo "# branch=$BRANCH commit=$SHA"
  [ -n "$DIRTY" ] && echo "# WARNING: uncommitted tracked changes -- SHA does not describe the code that ran"
  echo "# head: score = ( rad(P_v) - d_H(P_u,P_v) ) / rad(P_u)   <- NO temperature, no learned scalar"
  echo "#       161 head params: the pooler MLP alone. init_irange 1e-3."
  echo "#       pooling = softmax(MLP([log1p(age) | raw pos | rad])), width 32, unchanged"
  echo "#"
  echo "# WHAT IT IS. Numerator = the Gromov product with the source term dropped:"
  echo "#   (u|v)_o = (rad_u + rad_v - d)/2, and rad_u is constant within a query, so under"
  echo "#   per-query softmax CE it adds the same constant to every candidate and cancels from the"
  echo "#   loss AND the gradient (sum_c dL/ds_c = 0). What remains, rad_v - d, ranks by candidate"
  echo "#   DEPTH minus distance -- a deep candidate may be proportionally farther away."
  echo "#   Denominator reintroduces rad_u as a PER-QUERY TEMPERATURE: it cannot reorder (per-row"
  echo "#   positive divisor) but softmax is only SHIFT-invariant, not scale-invariant, so it"
  echo "#   modulates each query's entropy by the source's depth."
  echo "#"
  echo "# MEASURED BEFORE LAUNCH -- read the run against these, not against the claim:"
  echo "#   SCALE-RESPONSE IS NOT DEGREE-0. Rescaling E by k: spread 0.4547 / 0.4383 / 0.3720 /"
  echo "#     0.1648 at k = 0.25 / 0.5 / 1 / 2 -- a 2.8x FALL as the embedding expands, i.e. a mild"
  echo "#     CONTRACTION incentive. Degree-0 holds only in the Euclidean limit."
  echo "#     >>> so WATCH |E|mean for shrinkage, unlike the Gromov arms where it was scale-neutral."
  echo "#   DEPTH MODULATION IS REAL BUT SMALL. Source |p_u| 0.05 -> 0.95 (rad_u 0.10 -> 3.66) over"
  echo "#     100 candidates: entropy 4.5958 -> 4.6047 vs uniform 4.6052. Directionally as claimed"
  echo "#     (deeper -> flatter) but a 0.009-nat effect. What rad_u genuinely does is INVERT the"
  echo "#     spread ordering across source depths: without the divisor spread runs 0.056 -> 0.428"
  echo "#     -> 0.485 as the source deepens, with it 0.552 -> 0.532 -> 0.130."
  echo "#   NOT A FREE-LUNCH CHANNEL, unlike every other per-row temperature tried here. rad_u"
  echo "#     cannot move independently of the numerator: as P_u -> origin, d -> rad_v so"
  echo "#     (rad_v - d) -> 0 at rate rad_u*cos(theta) and the ratio tends to cos(theta). rad_u"
  echo "#     swept 6.2e-1 -> 2.0e-7 leaves spread 0.4644 / 0.4527 / 0.4514, maxprob 0.1442 /"
  echo "#     0.1408 / 0.1408. Contrast -rad_u*rad_v*d, where the same knob ran maxprob 0.167 ->"
  echo "#     0.982 with the ranking unchanged."
  echo "#   INIT through the real pooled path: CE 1.7796 vs log(6) = 1.7918, spread 0.2368,"
  echo "#     maxprob 0.1877, |grad E|max 0.60. Starts at chance, no saturation."
  echo "#"
  echo "# THIS IS RUN 2. Run 1 (patience 3) was TRUNCATED and its 0.4297 is not a ceiling. Its val"
  echo "#   ran 0.5004, 0.5156, 0.5092, 0.5017, 0.5053 -- it dipped two epochs then TURNED BACK UP"
  echo "#   at ep5, but patience 3 had expired since none beat the ep2 peak. Only the patience"
  echo "#   differs here: 3 -> 5. Same commit, same seed, same everything else."
  echo "#"
  echo "# WHAT RUN 1 SETTLED, so this one is not read against a stale prediction:"
  echo "#   The pre-launch bounded-spread objection was WRONG. It held that an un-tempered head"
  echo "#   cannot express confidence (spread only ~0.13-0.55 over 100 candidates) and would"
  echo "#   underfit like the other two un-tempered arms, which parked link at 1.46-1.60 with val"
  echo "#   FLAT (0.2969 and 0.2529). Instead run 1 drove link 1.3928 -> 1.1861 monotonically while"
  echo "#   val peaked at ep2 and DECLINED: memorisation, not underfit. This head reaches"
  echo "#   confidence without a temperature."
  echo "#   The CONTRACTION incentive also did not materialise: despite spread falling 2.8x as E"
  echo "#   expands (0.4547 -> 0.1648 for k = 0.25 -> 2), |E|mean GREW 0.015 -> 0.033 and |E|max"
  echo "#   0.104 -> 0.332."
  echo "#   Run 1 posted the best epoch-1 of all seven arms (test 0.4159, +0.059 over the next) and"
  echo "#   its ep1 val 0.5004 beat the tempered Gromov'''s best over 17 epochs (0.4747)."
  echo "#"
  echo "# WATCH HERE SPECIFICALLY: whether val recovers past 0.5156 after the ep3-4 dip. If it does,"
  echo "#   run 1 was purely a patience artifact. If it stalls in the 0.50-0.52 band and patience 5"
  echo "#   fires around ep7-9, the ep2 peak was real and this head genuinely peaks very early --"
  echo "#   which would make T*(rad_v - d)/rad_u the indicated follow-up, as a sharpness control on"
  echo "#   a head that already overfits rather than a rescue for one that underfits."
  echo "#"
  echo "# PRIOR ART, branch feature/gromov-product-head (numbers from stash titles; some at d16,"
  echo "#   logs deleted, so NOT directly comparable to d64 -- treat as ordering, not levels):"
  echo "#   radius-corrected rho_v                   0.5132"
  echo "#   negated control w.[+d, -rho_v]           0.4755 (still climbing)"
  echo "#   2-channel w.[-d, rho_v]                  0.4589"
  echo "#   3-weight ratio                           0.4284  (w1 collapsed 1 -> 0.008)"
  echo "#   scale-free (rho_u+rho_v-d)/(rho_u+rho_v) 0.3815"
  echo "#   Commit 68a17be9 there ALREADY ran s = rho_v - d, i.e. this numerator WITHOUT the rad_u"
  echo "#   divisor. The divisor is the new thing in this arm."
  echo "#"
  echo "# REFERENCES this session (YouTube d=64 K=5 seed 42, no pop bias, SAME pooler in each):"
  echo "#   geo_temp * (-d)                : 0.5625 @ep21  <- BASELINE, unbeaten"
  echo "#   -d / (rad_u * rad_v)           : 0.4399 @ep8"
  echo "#   -rad_u * rad_v * d             : 0.4264 @ep19"
  echo "#   geo_temp * (-d/(rad_u+rad_v))  : 0.3928 @ep12"
  echo "#   -d / (rad_u + rad_v)           : 0.2969 @ep6"
  echo "#   -d / rad_v                     : 0.2529 @ep6"
  echo "#   LB #1 GraphMixer               : 0.5887"
  echo "#"
  echo "# WATCH: (a) link -- if it parks ~1.45-1.60 while val stalls, this is the un-tempered"
  echo "#   regime repeating and the bounded spread is the cause;  (b) |E|mean CONTRACTING, which"
  echo "#   this head incentivises and the Gromov arms did not;  (c) whether val peaks then"
  echo "#   DECLINES (memorisation) or just goes flat (underfit) -- the two un-tempered arms went"
  echo "#   flat;  (d) record BOTH max test and test@val-checkpoint;  (e) patience is 3."
  echo "# ~100 s/epoch (70 train + 28 eval)."
  echo "# started=$(date '+%F %T')"
  echo "# cmd: $CMD"
  echo
} > "$LOG"
PYTHONUNBUFFERED=1 $CMD >> "$LOG" 2>&1
echo "[$(date '+%F %T')] DONE rc=$?  $(grep -E 'stopped_at_epoch|best_val_mrr|best_test_mrr' "$LOG" | tr -s ' ' | tr '\n' ' ')" >> "$LOG"
