#!/bin/bash
# YouTube d=64 K=5: TimeEncoder(age) + hop embedding pooler, geo_temp*(-d) score.
PY=/its/home/ms2420/tempest-embeddinng/venv/bin/python
WD=/its/home/ms2420/tempest-embeddinng
LOG=$WD/logs/time_encoder_frozen/d64_k5/run_1/YouTube.log
cd "$WD" || exit 1
mkdir -p "$(dirname "$LOG")"
SHA=$(git rev-parse --short HEAD); BRANCH=$(git rev-parse --abbrev-ref HEAD)
DIRTY=$(git status --porcelain --untracked-files=no | head -1)
CMD="$PY -u scripts/train_link_property_prediction.py --data-suite tgb-seq --dataset YouTube \
--d-emb 64 --k-train 5 --lr 1e-3 --num-epochs 100 --early-stop-patience 5 \
--d-time 32 --d-hop 4 --use-gpu --use-gpu-tempest"
{
  echo "# dataset=YouTube (NON-bipartite) d_emb=64 k_train=5  lr=1e-3 (single group)  seed=42"
  echo "# experiment=time_encoder_frozen cell=d64_k5 tag=run_1"
  echo "# branch=$BRANCH commit=$SHA"
  [ -n "$DIRTY" ] && echo "# WARNING: uncommitted tracked changes -- SHA does not describe the code that ran"
  echo "# head: score = geo_temp * (-d_H(P_u,P_v)), geo_temp LINEAR init 1.0  <- UNCHANGED baseline score"
  echo "#       pooling = softmax(MLP([TimeEncoder(age) | hop_emb(hop) | rad])), width 32"
  echo "#       d_time=32, d_hop=4 -> n_feat 37; head params 1274 TRAINABLE + 64 FROZEN"
  echo "#       TimeEncoder is FROZEN: the ladder is a fixed basis, no option to train it."
  echo "#"
  echo "# ONE VARIABLE vs the 0.5625 BASELINE: the pooler's INPUT ENCODING. The score, the walks,"
  echo "#   the optimiser, the lr and hidden_dim=32 are all identical. Features go from"
  echo "#   [log1p(age) | raw hop scalar | rad] (3) to [TimeEncoder(age) | hop_emb(hop) | rad] (37)."
  echo "#   hidden_dim stays pinned at 32 so input width moves without moving pooler capacity."
  echo "#"
  echo "# WHAT CHANGED STRUCTURALLY:"
  echo "#   WalkTokens now carries raw `timestamps` (t_edge) instead of precomputed `ages`; the age"
  echo "#     is derived in the pooler as cutoff - t_edge. Tempest's INT64_MAX seed sentinel is"
  echo "#     resolved to the cutoff at the boundary because cutoff - INT64_MAX overflows int64."
  echo "#     seed_mask and the edge-feature mask were rewritten off (edge_ts == cutoff), which is"
  echo "#     equivalent since the cutoff is EXCLUSIVE."
  echo "#   hop is now an EMBEDDING (max_walk_len+1 = 6 rows x 4), not an affine scalar. Hops run"
  echo "#     1..max_walk_len (1 = seed, 5 = oldest) with 0 = padding, masked out of the softmax."
  echo "#     The scalar could only express a monotone depth preference; a table can single out the"
  echo "#     seed slot. That is the main expressivity gain being tested."
  echo "#"
  echo "# >>> MEASURED HAZARD -- READ BEFORE INTERPRETING THIS RUN. <<<"
  echo "#   The frequency ladder is the plain TGAT 1/10^linspace(0,9,d_time) with NO floor at the"
  echo "#   timestamp grid. Commit 7c7c112a previously established that a channel whose period is"
  echo "#   shorter than 2x the grid spacing is BELOW NYQUIST and resolves nothing: every age is a"
  echo "#   multiple of the grid, so the channel is a deterministic hash of the grid index, not a"
  echo "#   time signal -- and it still looks healthy by variance, so no shape or parameter check"
  echo "#   catches it."
  echo "#   Measured on YouTube's own train split: 2,730,407 edges but only 175 DISTINCT timestamps,"
  echo "#   p10 gap 86,400 s -- a 24h grid. Nyquist floor = 172,800 s."
  echo "#     d_time=32  periods 6.28 .. 6.28e9   SUB-NYQUIST: 16/32   <- HALF the channels"
  echo "#     d_time=8                            SUB-NYQUIST:  4/8"
  echo "#   So 16 of 37 pooler input channels carry no resolvable signal on this dataset. This is"
  echo "#   being run deliberately as the UNFLOORED baseline. If it underperforms, flooring the"
  echo "#   ladder at the grid resolution is the indicated next arm, NOT a verdict on time encoding."
  echo "#"
  echo "# THIS IS THE FROZEN RE-RUN. One variable vs logs/time_encoder/ (killed ep9): the"
  echo "#   TimeEncoder's 64 parameters no longer train. Everything else identical."
  echo "#   That run trailed the baseline at EVERY epoch while its score side tracked it almost"
  echo "#   exactly (geo_temp and |E|mean within ~1% through ep7), so the pooler was the only"
  echo "#   variable:"
  echo "#     ep     1      2      3      4      5      6      7      8      9"
  echo "#     enc    0.1465 0.1924 0.2240 0.2498 0.2788 0.2979 0.3184 0.3313 0.3398"
  echo "#     base   0.1792 0.2230 0.2541 0.2792 0.3011 0.3192 0.3378 0.3498 0.3601"
  echo "#     gap   -0.033 -0.031 -0.030 -0.029 -0.022 -0.021 -0.019 -0.019 -0.020"
  echo "#   link was WORSE too through ep6, only dipping below from ep7 -- so the encoded pooler"
  echo "#   fit the TRAINING data worse: an optimisation deficit, NOT overfitting, despite 8x the"
  echo "#   head parameters. Freezing removes 64 params that were free to chase noise."
  echo "#"
  echo "# PRIOR ART -- an encoded pooler was tried before and LOST to the 3-scalar one:"
  echo "#   encoded pooler (TimeEncoding+pos-emb, 762p), single lr : 0.5487  (logs/encoded_single_lr)"
  echo "#   encoded + ts_quantum-floored ladder                    : 0.5487  (logs/encoded_tsquantum)"
  echo "#   encoded + LOG geo_temp                                 : 0.5609  (logs/encoded_logtemp)"
  echo "#   encoded, age+pos only                                  : 0.5410  (logs/encoded_age_pos)"
  echo "#   3-scalar [log1p(age), pos, rad] = THE BASELINE          : 0.5625"
  echo "#   57b0b310 already ran a FROZEN GraphMixer encoder once, before it was made trainable."
  echo "#   Different encoder and pos sizing, so treat all of these as a prior, not a result."
  echo "#"
  echo "# REFERENCES (YouTube d=64 K=5 seed 42, no pop bias):"
  echo "#   geo_temp * (-d), 3-scalar pooler : 0.5625 @ep21  <- THE NUMBER TO BEAT"
  echo "#   best no-pop arm on record        : 0.5793 (logage_zscore)"
  echo "#   parameter-free pooling rule, K=10: 0.5756"
  echo "#   LB #1 GraphMixer                 : 0.5887"
  echo "#"
  echo "# WATCH: (a) geo_temp -- the baseline ran 4.2 -> 41.6 and ESCAPED AT ep17 (val 0.4409 ->"
  echo "#   0.5168, test -> 0.5625 by ep21). Do NOT call this arm before that window;  (b) 1338 head"
  echo "#   params vs 162 is an 8x capacity jump -- watch for val peaking then declining"
  echo "#   (memorisation) rather than flattening;  (c) record BOTH max test and"
  echo "#   test@val-checkpoint -- val/test drift has flipped verdicts on this pipeline;"
  echo "#   (d) patience 5, cap 100."
  echo "# ~100 s/epoch (70 train + 28 eval)."
  echo "# started=$(date '+%F %T')"
  echo "# cmd: $CMD"
  echo
} > "$LOG"
PYTHONUNBUFFERED=1 $CMD >> "$LOG" 2>&1
echo "[$(date '+%F %T')] DONE rc=$?  $(grep -E 'stopped_at_epoch|best_val_mrr|best_test_mrr' "$LOG" | tr -s ' ' | tr '\n' ' ')" >> "$LOG"
