#!/bin/bash
# YouTube d=64 K=5: radius-NORMALISED distance, NO learned temperature.
#   s(u,v) = -d_H(P_u,P_v) / (rad(P_u) * rad(P_v))
PY=/its/home/ms2420/tempest-embeddinng/venv/bin/python
WD=/its/home/ms2420/tempest-embeddinng
LOG=$WD/logs/radius_quotient/d64_k5/run_1/YouTube.log
cd "$WD" || exit 1
mkdir -p "$(dirname "$LOG")"
SHA=$(git rev-parse --short HEAD); BRANCH=$(git rev-parse --abbrev-ref HEAD)
DIRTY=$(git status --porcelain --untracked-files=no | head -1)
CMD="$PY -u scripts/train_link_property_prediction.py --data-suite tgb-seq --dataset YouTube \
--d-emb 64 --k-train 5 --lr 1e-3 --num-epochs 50 --early-stop-patience 5 \
--use-gpu --use-gpu-tempest"
{
  echo "# dataset=YouTube (NON-bipartite) d_emb=64 k_train=5  lr=1e-3 (single group)  seed=42"
  echo "# experiment=radius_quotient cell=d64_k5 tag=run_1"
  echo "# branch=$BRANCH commit=$SHA"
  [ -n "$DIRTY" ] && echo "# WARNING: uncommitted tracked changes -- SHA does not describe the code that ran"
  echo "# head: score = -d_H(P_u,P_v) / (rad(P_u) * rad(P_v))   <- radii DIVIDE, no learned scalar"
  echo "#       161 head params: the pooler MLP alone. init_irange 1e-3, UNCHANGED."
  echo "#       pooling = softmax(MLP([log1p(age) | raw pos | rad])), width 32, unchanged"
  echo "#"
  echo "# ONE VARIABLE vs the product arm (d321d7d6): -r_u*r_v*d  becomes  -d/(r_u*r_v)."
  echo "#   Same init, same pooler, same walks, same optimiser, same lr."
  echo "#"
  echo "# WHY. Ranking in a query row is invariant to any POSITIVE MULTIPLICATIVE row constant,"
  echo "#   so rad(P_u) cannot move the MRR (verified: argsort identical at r_u = 0.01, 1, 100)."
  echo "#   Softmax is only SHIFT-invariant, NOT scale-invariant, so rad(P_u) DOES move the CE."
  echo "#   In the product arm that was a free lunch and it fired: link -50% for +0.069 test,"
  echo "#   and at ep1 link=1.7907 vs log(6)=1.79176 -- loss at CHANCE with MRR already 0.357."
  echo "#   Moving P_u ALONE, the quotient closes it: as P_u -> origin the temperature 1/rad(P_u)"
  echo "#   blows up but d -> rad(P_v), so d/rad(P_v) -> 1 for every candidate and the signal"
  echo "#   collapses at the same rate. float64: r_u over 1e-9..1.1 (temp 0.9 -> 5e8) leaves the"
  echo "#   logit spread pinned at 0.037 and maxprob at 0.170."
  echo "#"
  echo "# THE HYPOTHESIS THIS RUN IS ACTUALLY TESTING -- found AFTER the change was written:"
  echo "#   A GLOBAL scaling is NOT closed. Scale every embedding by k and the shape is preserved,"
  echo "#   so nothing collapses -- spread grows exactly as 1/k with the argsort IDENTICAL:"
  echo "#       k = 1, 0.2, 0.01, 1e-3  ->  spread 2.35, 11.89, 237.9, 2378.6   maxprob 0.24 -> 1.00"
  echo "#   So the escape route is INVERTED, not removed. The product form sharpens by EXPANDING"
  echo "#   (self-limiting: |E|max saturated at 0.93). This one sharpens by CONTRACTING, and the"
  echo "#   origin is not a barrier. Contraction only pays where ranking is already right, so:"
  echo "#   PREDICTION -- honest ranking early, then a contraction runaway once ranking is good"
  echo "#   enough that sharpening is the cheaper descent direction, with the SAME loss/MRR"
  echo "#   decoupling arriving later than in the product arm."
  echo "#   >>> |E|mean COLLAPSING TOWARD 0 IS THE SIGNATURE. That is the primary read on this"
  echo "#   >>> run, ahead of the MRR. In the product arm |E|mean rose 0.098 -> 0.675."
  echo "#"
  echo "# KNOWN RISK, accepted deliberately to keep this a one-variable A/B. The radii are now in"
  echo "#   a DENOMINATOR and irange stays 1e-3, so rad(pooled) ~ 0.02 and the head opens"
  echo "#   near-saturated. MEASURED at init through the real pooled path, d=64, 1+5 row:"
  echo "#     init CE = 39.19  vs log(6) = 1.79        <- confidently WRONG at step 0"
  echo "#     init maxprob = 0.968  (uniform 0.167)"
  echo "#     |grad E|max = 3.3e+02,  d/dr_u = -d/(r_u^2 * r_v) ~ 1e6"
  echo "#   Raising irange to 2e-2 / 5e-2 gives maxprob 0.569 / 0.344 and CE 2.60 / 1.92; that was"
  echo "#   measured and NOT applied. IF EPOCH 1 DIVERGES OR NaNs, raise irange before concluding"
  echo "#   anything about the score. Adam normalises by gradient scale, so it may well survive."
  echo "#"
  echo "# SHARPNESS CEILING, specific to this form: the triangle inequality through the origin"
  echo "#   gives |r_u - r_v| <= d <= r_u + r_v, so the logit spread is bounded by 2/rad(P_v)."
  echo "#   Ceiling 9.97 at |x|=0.1, 1.82 at |x|=0.5, 0.68 at |x|=0.9. This head can only be sharp"
  echo "#   while E stays COMPACT -- which is the same pressure as the contraction runaway above."
  echo "#"
  echo "# REFERENCES (YouTube d=64 K=5 seed 42, no pop bias, same pooler):"
  echo "#   geo_temp * (-d)          : 0.5625 @ep21  <- THE BASELINE (logage_scalar run_2)"
  echo "#   -rad_u * rad_v * d       : 0.4264 @ep19  <- the product arm, KILLED while creeping"
  echo "#   best no-pop arm on record: 0.5793 (logage_zscore)"
  echo "#   LB #1 GraphMixer         : 0.5887"
  echo "#"
  echo "# WATCH: (a) |E|mean FIRST -- collapse toward 0 confirms the contraction runaway;"
  echo "#   (b) link vs test decoupling, as in the product arm; (c) record BOTH max test and"
  echo "#   test@val-checkpoint; (d) NaN/inf in epoch 1 (see KNOWN RISK); (e) the product arm's"
  echo "#   ep1 test was 0.3572 -- a fast ep1 here means nothing, that arm had the fastest ep1"
  echo "#   of any YouTube run and still lost by 0.136."
  echo "# ~100 s/epoch (70 train + 28 eval)."
  echo "# started=$(date '+%F %T')"
  echo "# cmd: $CMD"
  echo
} > "$LOG"
PYTHONUNBUFFERED=1 $CMD >> "$LOG" 2>&1
echo "[$(date '+%F %T')] DONE rc=$?  $(grep -E 'stopped_at_epoch|best_val_mrr|best_test_mrr' "$LOG" | tr -s ' ' | tr '\n' ' ')" >> "$LOG"
