#!/bin/bash
# Patent d=64 K=5 on MASTER's pooler, single lr raised 1e-3 -> 3e-3.
PY=/its/home/ms2420/tempest-embeddinng/venv/bin/python
WD=/its/home/ms2420/tempest-embeddinng
LOG=$WD/logs/patent_split_optimizer/d64_k5/run_1/Patent.log
cd "$WD" || exit 1
mkdir -p "$(dirname "$LOG")"
SHA=$(git rev-parse --short HEAD); BRANCH=$(git rev-parse --abbrev-ref HEAD)
DIRTY=$(git status --porcelain --untracked-files=no | head -1)
CMD="$PY -u scripts/train_link_property_prediction.py --data-suite tgb-seq --dataset Patent \
--d-emb 64 --k-train 5 --lr 1e-3 --num-epochs 50 --early-stop-patience 5 \
--use-gpu --use-gpu-tempest"
{
  echo "# dataset=Patent (NON-bipartite) d_emb=64 k_train=5  lr=1e-3 (shared by both optimisers)  NO pop bias  seed=42"
  echo "# experiment=patent_split_optimizer cell=d64_k5 tag=run_1"
  echo "# branch=$BRANCH commit=$SHA"
  [ -n "$DIRTY" ] && echo "# WARNING: uncommitted tracked changes -- SHA does not describe the code that ran"
  echo "# head: score = geo_temp * (-d_H), geo_temp LINEAR init 1.0"
  echo "#       pooling = softmax(MLP([log1p(age) | raw pos | rad])), width 32, 162 head params"
  echo "#       nothing standardised; no dataset-derived constant in the pooler"
  echo "#"
  echo "# TWO CHANGES vs master, so this is not a single-factor A/B:"
  echo "#   (1) the popularity channel is REMOVED, not merely disabled (it was off in every"
  echo "#       TGB-Seq run anyway, so this should be inert -- if it is not, that is news)."
  echo "#   (2) TWO OPTIMISERS at one shared lr=1e-3: RiemannianAdam over the manifold parameter"
  echo "#       E, Adafactor over geo_temp and the NN pooler."
  echo "#"
  echo "# WHY ADAFACTOR HERE. Adam moves a parameter by ~lr per step REGARDLESS of its magnitude,"
  echo "#   so one rate cannot serve geo_temp (which must travel from 1.0 to Patent optimum ~170)"
  echo "#   and pooler weights (which live at ~0.5). Measured on torch 2.7.1, one tensor at three"
  echo "#   scales with a proportional gradient, 50 steps:"
  echo "#     scale 0.5   Adam moved 0.500 (100% of scale)   Adafactor 0.197 (39.5%)"
  echo "#     scale 5.0   Adam moved 0.500 ( 10% of scale)   Adafactor 1.975 (39.5%)"
  echo "#     scale 100   Adam moved 0.500 (0.5% of scale)   Adafactor 39.50 (39.5%)"
  echo "#   Adam absolute movement is identical at every scale; Adafactor moves each by the same"
  echo "#   fraction of itself. That is the pathology the lr-split commits were compensating for."
  echo "#"
  echo "# THE PATENT-SPECIFIC PRIOR. The field notes measured the original Patent collapse as an"
  echo "#   INPUT-SCALE defect: the pooler first-layer weight had to grow to ~31.4 before recency"
  echo "#   registered, 3.6 epochs at 1e-3, and the run died at ep4. Widening the fast lr group to"
  echo "#   include the pooler is what took Patent 0.1630 -> 0.2633. A scale-free update rule is"
  echo "#   the same fix without a hand-tuned second rate -- so this run tests whether the record"
  echo "#   is reachable WITHOUT per-group lr tuning."
  echo "#   Caveat: master features [log1p(age),pos,rad] already largely fix that imbalance"
  echo "#   (log1p(age) std ~1.5 vs pos ~1.4 on Patent), which is why this config scores 0.2170"
  echo "#   at a single Adam rate. So the headroom Adafactor can recover may be small."
  echo "#"
  echo "# COST: +6.1 ms/step benchmarked at Patent scale (94.9 -> 101.0 ms), about +55 s on a"
  echo "#   ~890 s epoch. The RiemannianAdam step over 143M rows dominates at ~95 ms."
  echo "#"
  echo "# PATENT REFERENCES (d=64 K=5 seed 42, from logs/*/d64_k5/*/Patent.log):"
  echo "#   split lr, E@1e-3 temp+pooler@1e-2, mnia scalar pooler : 0.2633 @ep4   <- record"
  echo "#   encoded pooler (TimeEncoding+pos-emb, 762p), single lr: 0.2506 @ep5"
  echo "#   parameter-free softmax(rec+pos), 0 params             : 0.2413 @ep13"
  echo "#   [log1p(age),pos,rad] 161p single Adam 1e-3            : 0.2170 @ep4   <- THE BASELINE"
  echo "#   same features, single Adam 3e-3                      : 0.2370 @ep4, STILL RISING when"
  echo "#     handed to another agent -- a floor, not a peak. Raising the base rate helps here."
  echo "#   same features, 2 layers 1218p                         : 0.1868 @ep6"
  echo "#   mnia scalar pooler, single 1e-3                       : 0.1630 @ep1, died ep4"
  echo "#"
  echo "# STRUCTURAL CONTEXT: 99.9% of Patent's source queries are cold -- 20 valid tokens from"
  echo "#   51,200 slots -- because every citation carries the citing patent's filing date and the"
  echo "#   cutoff is strictly t_edge < t_query. P_u is never a pooled centroid here; the pooler"
  echo "#   only ever acts on the candidate side. Do not read pooler results from Patent as if"
  echo "#   both sides were live."
  echo "#"
  echo "# WATCH: (a) DO NOT READ BEFORE EPOCH 3 -- on Patent the epoch-1 ranking is close to"
  echo "#   inverted; the run that died had the best ep1 (0.1630) and the record opened at 0.0459."
  echo "#   Separation is reliable by ep4-5;  (b) RECORD BOTH max test AND test@val-checkpoint --"
  echo "#   across the ten best Patent runs, peak-val to peak-test correlation is -0.088, so the"
  echo "#   checkpoint selects close to arbitrarily among good candidates;  (c) |E|mean -- runs"
  echo "#   that worked reached 0.166-0.199, ones that failed stalled at 0.106-0.115;"
  echo "#   (d) divergence -- 3e-3 on a Riemannian ManifoldParameter is untested; a blow-up is a"
  echo "#   real outcome and is itself informative."
  echo "# ~970 s/epoch (889 train + 80 eval). Patent peaks ep4-5 and dies by ep8-13: budget 2-3 h."
  echo "# started=$(date '+%F %T')"
  echo "# cmd: $CMD"
  echo
} > "$LOG"
PYTHONUNBUFFERED=1 $CMD >> "$LOG" 2>&1
echo "[$(date '+%F %T')] DONE rc=$?  $(grep -E 'stopped_at_epoch|best_val_mrr|best_test_mrr' "$LOG" | tr -s ' ' | tr '\n' ' ')" >> "$LOG"
