#!/bin/bash
# YouTube d=64 K=5: normalised Gromov product, NO temperature.
#   s(u,v) = -d_H(P_u,P_v) / (rad(P_u) + rad(P_v))
PY=/its/home/ms2420/tempest-embeddinng/venv/bin/python
WD=/its/home/ms2420/tempest-embeddinng
LOG=$WD/logs/gromov_notemp/d64_k5/run_1/YouTube.log
cd "$WD" || exit 1
mkdir -p "$(dirname "$LOG")"
SHA=$(git rev-parse --short HEAD); BRANCH=$(git rev-parse --abbrev-ref HEAD)
DIRTY=$(git status --porcelain --untracked-files=no | head -1)
CMD="$PY -u scripts/train_link_property_prediction.py --data-suite tgb-seq --dataset YouTube \
--d-emb 64 --k-train 5 --lr 1e-3 --num-epochs 100 --early-stop-patience 3 \
--use-gpu --use-gpu-tempest"
{
  echo "# dataset=YouTube (NON-bipartite) d_emb=64 k_train=5  lr=1e-3 (single group)  seed=42"
  echo "# experiment=gromov_notemp cell=d64_k5 tag=run_1"
  echo "# branch=$BRANCH commit=$SHA"
  [ -n "$DIRTY" ] && echo "# WARNING: uncommitted tracked changes -- SHA does not describe the code that ran"
  echo "# head: score = -d_H(P_u,P_v) / (rad(P_u) + rad(P_v))   <- NO temperature, no learned scalar"
  echo "#       161 head params: the pooler MLP alone. init_irange 1e-3, unchanged."
  echo "#       pooling = softmax(MLP([log1p(age) | raw pos | rad])), width 32, unchanged"
  echo "#"
  echo "# ONE VARIABLE vs gromov_temp (e9b417d3, 0.3928 @ep12): geo_temp is DELETED. Similarity,"
  echo "#   pooler, init, optimiser and lr are identical."
  echo "#"
  echo "# THE HYPOTHESIS. The tempered arm's failure was MEMORISATION, not underfitting: link fell"
  echo "#   to 0.0914 while val peaked at ep12 and then declined five straight epochs to a natural"
  echo "#   stop at ep17. The temperature is the ONLY thing that can turn a bounded similarity into"
  echo "#   confident predictions, so it is what made that possible. Capping confidence may act as"
  echo "#   a regulariser and keep the geometry improving instead of the logits sharpening."
  echo "#"
  echo "# THE COST, and this is the thing to read the run against. The similarity is bounded in"
  echo "#   [0,1] with effective spread ~0.25 at moderate radii (measured [0.5555,0.8136] at init)"
  echo "#   and 0.10 near the boundary; even a perfectly separated configuration cannot exceed"
  echo "#   spread 1. That caps CE roughly 0.16-0.47 below chance (log 6 = 1.7918) and it can never"
  echo "#   approach the tempered arm's 0.091. It also removes gradient FOCUSING -- on the geo_temp"
  echo "#   head, gradient mass on an unsolved row goes 23% -> 98% -> 100% as T goes 1 -> 5 -> 15;"
  echo "#   with no T every example keeps roughly equal weight forever."
  echo "#   The other un-tempered head (-d/rad_v) stalled at link 1.60 / test 0.2529, worst of five"
  echo "#   arms, for exactly this reason. NOT a clean precedent though: it also lacked a"
  echo "#   rank-relevant rad_u and chased the boundary (|E|max 0.083 -> 0.958, bulk frozen at"
  echo "#   0.024). Neither applies here."
  echo "#"
  echo "# WHAT THE SIMILARITY IS. d/(rad_u+rad_v) == 1 - 2*(u|v)_o/(rad_u+rad_v) where"
  echo "#   (u|v)_o = (rad_u+rad_v-d)/2 is the Gromov product -- in a tree, the depth of u and v's"
  echo "#   LOWEST COMMON ANCESTOR from the origin. Ranks by the SHARE of each node's root-path the"
  echo "#   two have in common. Scale-invariant, so neither the expansion exploit (-rad_u*rad_v*d,"
  echo "#   margin ~ k^3) nor the contraction exploit (-d/(rad_u*rad_v), margin ~ 1/k) exists."
  echo "#   rad_u is RANK-RELEVANT here: additively it does not factor out of the row."
  echo "#"
  echo "# NOT TESTED HERE, and still the leading explanation for the 0.3928 plateau: |E| CAPACITY."
  echo "#   The baseline escapes at |E|mean 0.246; the tempered Gromov arm ENDED at 0.086. Hyperbolic"
  echo "#   volume grows exponentially with radius, and scaling a fixed configuration outward"
  echo "#   REORDERS it past |x| ~ 0.4 (measured), so expansion buys representational capacity, not"
  echo "#   merely temperature. Raising init_irange is a separate one-variable test, deliberately"
  echo "#   NOT bundled in. If this run also plateaus near 0.39 with |E|mean ~0.08, that is further"
  echo "#   evidence for capacity and against the temperature being the culprit."
  echo "#"
  echo "# REFERENCES (YouTube d=64 K=5 seed 42, no pop bias, SAME pooler in every arm):"
  echo "#   geo_temp * (-d)                : 0.5625 @ep21  <- BASELINE, unbeaten"
  echo "#   -d / (rad_u * rad_v)           : 0.4399 @ep8"
  echo "#   -rad_u * rad_v * d             : 0.4264 @ep19"
  echo "#   geo_temp * (-d/(rad_u+rad_v))  : 0.3928 @ep12  <- the tempered version of THIS head"
  echo "#   -d / rad_v                     : 0.2529 @ep6   <- the other un-tempered head"
  echo "#   LB #1 GraphMixer               : 0.5887"
  echo "#"
  echo "# WATCH: (a) link -- if it parks near 1.5-1.6 and val stalls, this is the -d/rad_v failure"
  echo "#   repeating and the bounded-similarity cap is the cause;  (b) whether val still peaks then"
  echo "#   DECLINES. If it does, removing the temperature did not stop the memorisation and the"
  echo "#   hypothesis is wrong;  (c) |E|mean -- if it again sits ~0.08 while the baseline needs"
  echo "#   0.246, capacity is the live explanation regardless of what the temperature does;"
  echo "#   (d) record BOTH max test and test@val-checkpoint;  (e) every arm in this series started"
  echo "#   fast; do not call it before the baseline's ep17 window."
  echo "# ~100 s/epoch (70 train + 28 eval). 100 epochs / patience 3, set deliberately."
  echo "# started=$(date '+%F %T')"
  echo "# cmd: $CMD"
  echo
} > "$LOG"
PYTHONUNBUFFERED=1 $CMD >> "$LOG" 2>&1
echo "[$(date '+%F %T')] DONE rc=$?  $(grep -E 'stopped_at_epoch|best_val_mrr|best_test_mrr' "$LOG" | tr -s ' ' | tr '\n' ' ')" >> "$LOG"
