#!/bin/bash
# WikiLink d=64 K=5 on feature/pooler-lr: NN pooler in its own param group at 1e-2.
PY=/its/home/ms2420/tempest-embeddinng/venv/bin/python
WD=/its/home/ms2420/tempest-embeddinng
LOG=$WD/logs/wikilink_lr3e3/d64_k5/run_1/WikiLink.log
cd "$WD" || exit 1
mkdir -p "$(dirname "$LOG")"
SHA=$(git rev-parse --short HEAD); BRANCH=$(git rev-parse --abbrev-ref HEAD)
DIRTY=$(git status --porcelain --untracked-files=no | head -1)
CMD="$PY -u scripts/train_link_property_prediction.py --data-suite tgb-seq --dataset WikiLink \
--d-emb 64 --k-train 5 --lr 3e-3 --num-epochs 50 --early-stop-patience 5 \
--use-gpu --use-gpu-tempest"
{
  echo "# dataset=WikiLink (NON-bipartite) d_emb=64 k_train=5  lr=3e-3 (SINGLE group)  NO pop bias  seed=42"
  echo "# experiment=wikilink_lr3e3 cell=d64_k5 tag=run_1"
  echo "# branch=$BRANCH commit=$SHA"
  [ -n "$DIRTY" ] && echo "# WARNING: uncommitted tracked changes -- SHA does not describe the code that ran"
  echo "# head: score = geo_temp * (-d_H), geo_temp LINEAR init 1.0, 162 head params"
  echo "#       pooling = softmax(MLP([log1p(age) | raw pos | rad])), width 32, depth 1"
  echo "#       nothing standardised; no dataset-derived constant in the pooler"
  echo "#"
  echo "# THE ONE VARIABLE vs master: lr 1e-3 -> 3e-3, single param group. Nothing else changed."
  echo "#"
  echo "# WHY: lr had never been varied on this suite -- all ~30 TGB-Seq runs used 1e-3. Raising"
  echo "#   it on PATENT took master from 0.2170 @ep4 (its own converged peak) to 0.2370 @ep4 and"
  echo "#   still climbing when that run was handed off: +0.0200 from one number, 4th on the"
  echo "#   all-time Patent table, no divergence on the Riemannian ManifoldParameter."
  echo "#   Patent geometry at 3e-3: |E|mean 0.163 / 0.245 / 0.281 / 0.301 by epoch, past every"
  echo "#   run in the Patent field-notes table by epoch 2."
  echo "#"
  echo "# THE RISK HERE IS SPECIFIC AND WORTH WATCHING. WikiLink already drives embeddings hard"
  echo "#   at 1e-3: the single-lr arm hit |E|max 0.971 by ep6, and the pooler-split arm reached"
  echo "#   |E|max 0.99+ from ep4 and |E|mean 0.888 by ep14 -- pressed against the Poincare"
  echo "#   boundary at 1.0. This run triples the rate on E ITSELF, so it should arrive there in"
  echo "#   roughly a third the epochs. geoopt projects back onto the ball, so the failure mode is"
  echo "#   not a crash but saturation: |E|max pinned at ~1.0 with the geometry unable to separate"
  echo "#   anything further. If |E|mean passes ~0.9 in the first few epochs, expect that."
  echo "#"
  echo "# WIKILINK REFERENCES (d=64, K=5, seed 42, no pop bias):"
  echo "#   THIS CONFIG at lr=1e-3 (the direct baseline)   : 0.6282 @ep6 -- KILLED still rising,"
  echo "#     a FLOOR not a peak. Was ahead of the mnia arm at every epoch (+0.0046 at ep6)."
  echo "#   NN pooler [rec,pos,rad] mnia scale, single lr   : 0.6313 @ep11, stop ep14, 162 par"
  echo "#   fixed pooler, no pooling temp, linear geo_temp  : 0.5430 @ep7 (converged)"
  echo "#   fixed pooler, 1-param pooling temp             : 0.5828 @ep7"
  echo "#   fixed pooler, EXP geo_temp                     : 0.6108 @ep8"
  echo "#   encoded pooler + LOG temp                      : 0.7014 @ep6 -- also KILLED while"
  echo "#     rising, and on a different branch (log temp), so NOT comparable to this run."
  echo "#   LB #1 TGN = 0.6294.   Our record 0.7904 @ep44 (a much larger head)."
  echo "#"
  echo "#   pooler @1e-2 split, same features              : 0.6654 @ep12 -- killed at ep14 with"
  echo "#     patience 2/5, also a FLOOR. Beat LB #1 TGN by +0.036. That arm is the one to beat."
  echo "#"
  echo "# PRIOR EVIDENCE ON RAISING RATES, and it is mixed:"
  echo "#   Patent, base lr 3e-3        : +0.0200 over baseline, still rising when handed off."
  echo "#   WikiLink, pooler @1e-2      : +0.037 over the same-features single-lr floor."
  echo "#   Patent, pooler @1e-2 alone  : 0.1644, WORSE than that dataset baseline of 0.2170."
  echo "#   Three datasets have given three different answers to raising a rate, so this is not"
  echo "#   a settled lever -- it is being re-measured per dataset."
  echo "#"
  echo "# WHY IT MIGHT STILL PAY HERE: the mechanism the split addresses is a pooler whose"
  echo "#   first-layer weights must travel before its features are usable. On master's features"
  echo "#   that imbalance is already fixed -- log1p(age) and pos are both order 1 -- so a null"
  echo "#   result is entirely plausible and would be worth recording as such."
  echo "#"
  echo "# WATCH: (a) |E|mean and |E|max FIRST -- saturation is the expected failure mode, see above;"
  echo "#   (b) whether it clears 0.6282 (its own baseline at 1e-3), then 0.6313, then 0.6654,"
  echo "#   then LB #1 0.6294;  (b) geo_temp -- on WikiLink it RISES then RETREATS (13.9 -> 15.4"
  echo "#   -> 13.1 -> 11.3 -> 10.0 -> 9.0 on the single-lr arm) while |E|mean expands, the"
  echo "#   opposite of YouTube. A fast pooler should not change that; if it does, note it;"
  echo "#   (c) no escape -- WikiLink decelerates smoothly from ep1, so a jump would be news;"
  echo "#   (d) val/test drift."
  echo "# Record BOTH test@val-checkpoint AND max test observed."
  echo "# ~30 min/epoch (25 train + 5 eval). Prior WikiLink runs: 7.9 h for 14 epochs. Patience 5"
  echo "#   here, so budget 8-14 h -- this is the overnight run."
  echo "# started=$(date '+%F %T')"
  echo "# cmd: $CMD"
  echo
} > "$LOG"
PYTHONUNBUFFERED=1 $CMD >> "$LOG" 2>&1
echo "[$(date '+%F %T')] DONE rc=$?  $(grep -E 'stopped_at_epoch|best_val_mrr|best_test_mrr' "$LOG" | tr -s ' ' | tr '\n' ' ')" >> "$LOG"
