#!/bin/bash
# YouTube d=64 K=5: normalised Gromov product + one global learned temperature.
#   s(u,v) = geo_temp * ( -d_H(P_u,P_v) / (rad(P_u) + rad(P_v)) )
PY=/its/home/ms2420/tempest-embeddinng/venv/bin/python
WD=/its/home/ms2420/tempest-embeddinng
LOG=$WD/logs/gromov_temp/d64_k5/run_1/YouTube.log
cd "$WD" || exit 1
mkdir -p "$(dirname "$LOG")"
SHA=$(git rev-parse --short HEAD); BRANCH=$(git rev-parse --abbrev-ref HEAD)
DIRTY=$(git status --porcelain --untracked-files=no | head -1)
CMD="$PY -u scripts/train_link_property_prediction.py --data-suite tgb-seq --dataset YouTube \
--d-emb 64 --k-train 5 --lr 1e-3 --num-epochs 50 --early-stop-patience 5 \
--use-gpu --use-gpu-tempest"
{
  echo "# dataset=YouTube (NON-bipartite) d_emb=64 k_train=5  lr=1e-3 (single group)  seed=42"
  echo "# experiment=gromov_temp cell=d64_k5 tag=run_1"
  echo "# branch=$BRANCH commit=$SHA"
  [ -n "$DIRTY" ] && echo "# WARNING: uncommitted tracked changes -- SHA does not describe the code that ran"
  echo "# head: score = geo_temp * ( -d_H(P_u,P_v) / (rad(P_u) + rad(P_v)) )"
  echo "#       162 head params: pooler MLP + ONE global scalar. geo_temp LINEAR, init 1.0."
  echo "#       pooling = softmax(MLP([log1p(age) | raw pos | rad])), width 32, unchanged"
  echo "#"
  echo "# ONE VARIABLE vs THE BASELINE. geo_temp is parameterised exactly as in the"
  echo "#   geo_temp*(-d) baseline -- linear, init 1.0, same optimiser, same lr. The ONLY"
  echo "#   difference is the similarity: -d becomes -d/(rad_u+rad_v). That makes this the"
  echo "#   first arm in this series that is a clean single-factor A/B against 0.5625."
  echo "#"
  echo "# THE SIMILARITY IS THE NORMALISED GROMOV PRODUCT. Verified identity:"
  echo "#     d/(rad_u+rad_v)  ==  1 - 2*(u|v)_o/(rad_u+rad_v),   (u|v)_o = (rad_u+rad_v-d)/2"
  echo "#   (u|v)_o is, in a tree, the depth of u and v's LOWEST COMMON ANCESTOR seen from the"
  echo "#   origin. So this ranks by the SHARE of each node's root-path the two have in common --"
  echo "#   the tree analogue of cosine similarity, and the natural similarity on a hyperbolic"
  echo "#   embedding. Bounded in [0,1]; measured on a real forward, [0.5555, 0.8136]."
  echo "#"
  echo "# EVERY TERM EARNS ITS PLACE, which was not true of the three preceding heads:"
  echo "#   SCALE-INVARIANT (degree-1 over degree-1): a global rescale of E changes the logits by"
  echo "#     nothing, so neither prior exploit exists. -rad_u*rad_v*d sharpened by EXPANDING"
  echo "#     (margin ~ k^3) and DID: link -50% for +0.069 test. -d/(rad_u*rad_v) could sharpen by"
  echo "#     CONTRACTING (margin ~ 1/k)."
  echo "#   rad_u IS RANK-RELEVANT here: additively it does not factor out of the row, since"
  echo "#     d/dr_u of d_i/(r_u+r_v_i) = -d_i/(r_u+r_v_i)^2 differs per candidate. In the product"
  echo "#     and quotient forms rad_u was a per-row constant -- it could not reorder anything and"
  echo "#     existed only to leak temperature."
  echo "#"
  echo "# WHY THE TEMPERATURE IS BACK. A bounded similarity through a softmax cannot express"
  echo "#   confidence: the effective spread of d/(rad_u+rad_v) is ~0.25 at moderate radii and"
  echo "#   0.10 near the boundary, capping CE only 0.16-0.24 below chance (log 6 = 1.792). The"
  echo "#   preceding arm (-d/rad_v, NO scalar at all) stalled at link 1.60 / test 0.2529, worst of"
  echo "#   four heads, with headroom to CE ~0.52 it never used. Same reason SimCLR / CLIP /"
  echo "#   InfoNCE all divide cosine by a temperature instead of feeding it raw."
  echo "#"
  echo "# WHY A GLOBAL SCALAR IS SAFE WHERE A PER-ROW RADIUS WAS NOT -- the lesson of all four arms."
  echo "#   The pathology was never 'having a temperature', it was having a PER-ROW one: each query"
  echo "#   moves its own knob in its own favour and nothing cancels. A shared scalar is"
  echo "#   self-regulating -- correctly- and incorrectly-ranked rows pull it opposite ways on the"
  echo "#   same parameter (verified: 6 correct rows want T up, 2 wrong rows outvote them). It also"
  echo "#   restores focusing: gradient mass on an unsolved row goes 23% -> 98% -> 100% as"
  echo "#   T goes 1 -> 5 -> 15."
  echo "#"
  echo "# INIT, measured through the real pooled path: CE 1.7820 vs log(6)=1.7918 (at chance),"
  echo "#   |grad E|max 0.30, geo_temp.grad -0.0089 (temperature rises). No saturation, unlike the"
  echo "#   two-radius quotient (CE 39.19) -- degree-0 means irange cannot set the sharpness."
  echo "#"
  echo "# REFERENCES (YouTube d=64 K=5 seed 42, no pop bias, SAME pooler in every arm):"
  echo "#   geo_temp * (-d)        : 0.5625 @ep21  <- THE BASELINE, same temperature machinery"
  echo "#   -d / (rad_u * rad_v)   : 0.4399 @ep8"
  echo "#   -rad_u * rad_v * d     : 0.4264 @ep19"
  echo "#   -d / rad_v             : 0.2529 @ep6   <- no temperature at all"
  echo "#   best no-pop arm        : 0.5793 (logage_zscore)"
  echo "#   LB #1 GraphMixer       : 0.5887"
  echo "#"
  echo "# WATCH: (a) geo_temp -- it must climb. The baseline ran 4.2 -> 41.6 over 26 epochs and"
  echo "#   escaped at ep17 with geo_temp ~28. Here the similarity spread is ~0.25 rather than the"
  echo "#   baseline's raw distances, so geo_temp must reach a LARGER value for the same logit"
  echo "#   sharpness -- do not read its absolute value against the baseline's, read logit spread;"
  echo "#   (b) link should now be able to fall well below chance, unlike the previous arm;"
  echo "#   (c) |E|mean should be IRRELEVANT to sharpness (degree-0) -- if the geometry still runs"
  echo "#   to the boundary, something outside this analysis drives it. The previous arm sent"
  echo "#   |E|max 0.083 -> 0.958 while |E|mean sat at 0.024;"
  echo "#   (d) record BOTH max test and test@val-checkpoint;"
  echo "#   (e) every prior arm in this series started fast and lost. Do NOT call this before the"
  echo "#   baseline's ep17 escape window."
  echo "# ~100 s/epoch (70 train + 28 eval). Budget ~50 min to reach ep30."
  echo "# started=$(date '+%F %T')"
  echo "# cmd: $CMD"
  echo
} > "$LOG"
PYTHONUNBUFFERED=1 $CMD >> "$LOG" 2>&1
echo "[$(date '+%F %T')] DONE rc=$?  $(grep -E 'stopped_at_epoch|best_val_mrr|best_test_mrr' "$LOG" | tr -s ' ' | tr '\n' ' ')" >> "$LOG"
